name: CI/CD Pipeline

# run-name: ${{ github.actor }} is testing out GitHub Actions

on: push

jobs:
  Run-Unit-Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install packages from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyTest Unit Suite
        run: |
          pytest tests

  Issue-On-Unit-Test-Fail:
    needs: Run-Unit-Test-Suite
    runs-on: ubuntu-latest
    steps:
      - name: Test Issue-On-Unit-Test-Fail
        run: |
          echo "Issue-On-Unit-Test-Fail works!!!"
