name: CI/CD Pipeline

# run-name: ${{ github.actor }} is testing out GitHub Actions

on: push

jobs:
  Run-Unit-Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install packages from requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Verify pip packages have been installed
        run: |
          pip list