name: CI/CD Pipeline

# run-name: ${{ github.actor }} is testing out GitHub Actions

on: push

permissions: write-all

jobs:
  Run-Unit-Test-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install packages from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate Unit Test Suite Report
        continue-on-error: true
        run: |
          pytest tests -m "int_input" --html=./html_reports/unit_test/report.html
      - name: Commit Unit Test Suite Report to branch
        uses: EndBug/add-and-commit@v9
        with: 
          add: './html_reports/unit_test'
          default_author: github_actions
          message: '[no ci] Saving Unit Test Suite Report to branch'
          push: origin ${{ github.ref }} --force

  Issue-On-Unit-Test-Fail:
    needs: Run-Unit-Test-Suite
    runs-on: ubuntu-latest
    steps:
      - name: Test Issue-On-Unit-Test-Fail
        run: |
          echo "Issue-On-Unit-Test-Fail works!!!"